openapi: 3.0.3
info:
  title: ScribeMate API
  version: 0.1.0
  description: >
    Backend API for ScribeMate MVP.
    Simple authentication system for user management.

servers:
  - url: https://yourdomain.com/api
    description: Production
  - url: http://localhost:3001/api
    description: Local development

tags:
  - name: Auth

components:
  schemas:
    Error:
      type: object
      properties:
        status:
          type: string
          example: error
        message:
          type: string
          example: Invalid credentials
      required: [status, message]

    UserProfile:
      type: object
      properties:
        id:
          type: string
          format: uuid
        username:
          type: string
        full_name:
          type: string
        role:
          type: string
          enum: [coordinator, carer]
        created_at:
          type: string
          format: date-time
      required: [id, username, full_name, role, created_at]

    LoginRequest:
      type: object
      properties:
        username:
          type: string
        password:
          type: string
      required: [username, password]

    LoginSuccess:
      type: object
      properties:
        status:
          type: string
          example: success
        profile:
          $ref: "#/components/schemas/UserProfile"
      required: [status, profile]

    LogoutSuccess:
      type: object
      properties:
        status:
          type: string
          example: success
        logged_out_at:
          type: string
          format: date-time
      required: [status, logged_out_at]

paths:
  /auth/login:
    post:
      tags: [Auth]
      summary: Authenticate user credentials
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LoginRequest"
      responses:
        "200":
          description: Credentials valid
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/LoginSuccess"
        "401":
          description: Username or password incorrect
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
              example: { status: error, message: Invalid username or password }
        "429":
          description: Excessive request rate (rate-limited only in production hardening)
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /auth/logout:
    post:
      tags: [Auth]
      summary: End current session
      parameters:
        - name: user_id
          in: query
          required: true
          schema:
            type: string
            format: uuid
          description: User identity for authorization
      responses:
        "200":
          description: Logged out
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/LogoutSuccess"
        "401":
          description: Unknown or invalid user_id
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
